= Rapport d'avancement pour le PAN3

== ETAT ACTUEL DES MODULES

=== Module IDB (identification par bracelet) - Adrien Maes et Nicolas Jow

Nous avons codé en python la reconnaissance d'image. La fonction python est fonctionnelle. Le module est prêt à être intégré au code du robot.

=== Module COMCS (communication client-serveur) - Adrien Maes et Florian Le Mouël

Ce module se décompose en deux sous parties : une partie gestion interne du serveur et de la base de donnée utilisée, et une partie gérant les intéractions JAVA-JAVA et JAVA-PYTHON avec l'application Android et le robot.
Le minimum de fonctionnalités pour le projet est fonctionnel : création d'une session, ajout d'enfants, démarrage et arrêt d'une activité. Le lien entre le robot et le serveur qui analyse les images est lui aussi assuré.

*Partie BDD et serveur*

Le SGBD est installé (MariaDB dans un conteneur Docker) et fonctionnel, le code Java permettant l'édition d'une base de donnée est implémenté.
Pour l'instant, le code serveur tourne sur un ordinateur portable.
Le code Java permettant d'exécuter du code Python et de l'analyser est implémenté (pour faire tourner le module RECOD).

*Partie interface*

Les communications entre le serveur et l'application et entre le serveur et le robot sont parfaitement fonctionnelles, les échanges de données se font au format JSON et les images sont bien transmises entre le robot et le serveur.

=== Module reconnaissance d'images - Victor Masiak et Nicolas Jow

Après le PAN2, nous avons cherché à améliorer les performances du réseau, principalement en terme de vitesse. Nous nous sommes intéressés à divers implémentations de réseaux, que nous avons essayées. Nous nous sommes notamment attardés sur le projet https://github.com/jwyang/faster-rcnn.pytorch, mais n’arrivons pas à le faire fonctionner pour le moment, à cause de divers problèmes d’installations et de dépendances.

Nous continuons de chercher comment résoudre ces problèmes. En parallèle, nous nous intéressons à d’autres projets, notamment :
* https://github.com/pedropro/TACO
* https://github.com/matterport/Mask_RCNN
Nous rencontrons là encore des problèmes d’installations et de dépendances, que nous cherchons à résoudre.

Nous considérons également désormais le réseau conseillé par notre expert : Détectron 2 (https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5#scrollTo=QHnVupBBn9eR) en espérant ne pas rencontrer les mêmes difficultés de version pour son installation.

Pour PAN3, nous avions donc prévu d’utiliser le réseau Inception V3, associé à une méthode de balayage. Celui-ci fonctionne très bien en terme d’efficacité des détections, mais est extrêmement lent (trop pour pouvoir traiter les images en temps réel). Aucune modification n’y a été apportée depuis le PAN2, sauf quelques modifications mineures pour l’intégration.


== PLAN DE TRAVAIL POUR LE PAN 4

=== Module IDB

La partie code étant terminée, la seule chose restante à faire est la création des bracelets. Pour l'instant nous utilisons des bracelets en papier. Nous cherchons un moyen d'avoir des vrais bracelets mais si cela n'est pas possible nous resterons sur les bracelets en papier.

=== Module COMCS

Le système de statistiques en temps réel n'est pas implémenté. De plus il n'est pas non plus possible de consulter les statistiques depuis l'application ou depuis un site web.
Ceci est donc notre objectif pour le PAN 4.
En outre, pour l'instant nous ne travaillons qu'avec un seul robot et une seule application. Si nous avons le temps, nous envisageons d'implémenter la possibilité d'avoir plusieurs comptes (ce qui implique entre autre la création de base de donnée et la gestion de l'authentification des utilisateurs).

