= Rapport d’avancement du groupe “3.2”
PACT groupe 3.2 (Les plus beaux)
ifdef::env-gitlab,env-browser[:outfilesuffix: .adoc]
:doctype: book
:stem: latexmath
:source-highlighter: coderay
:toc-title: Table des matières
:toc: macro
:sectnums:
:imagesdir: images


// Partie non numérotée
:sectnums!:
== « Nom du groupe »

=== Membres du groupe

* Adrien Maes
* Florian Le Mouël
* Lola Vitrac
* Nicolas Jow
* Pierre Gimalac
* Romain Louvet
* Victor Masiak

=== Tuteur

* Jean-Claude Dufourd

=== Encadrant génie logiciel

* Attilio Fiandrotti

== Résumé du sujet choisi en français (PAN1)

*_Note: 15 lignes max_*

Décrire votre projet sans le scénariser : De quoi s’agit-il ? En quoi
cette idée est compatible avec le thème de PACT ? Qu’est ce qu’il
permettrait de faire de façon générale.

Il s'agit d'un petit robot qui recherche et signale la présence des déchets dans un  environnement défini. Celui-ci peut également décider de ramener les déchets à proximité de la poubelle la plus proche lorsque personne n'est présent autour de lui. Des enfants doivent alors intervenir pour jeter le déchet dans la bonne poubelle.
Ce projet a pour but de contribuer à la propreté de nos environnements. En particulier, le robot présente une optique éducative: il servirait a priori lors d'activités pédagogiques organisées par les enseignants 
(principalement en primaire) dans le but de sensibiliser les enfants au tri selectif et à la propreté en général.


== English Summary (PAN1)

*_Note : 15 lignes max, version anglaise du texte précédent_*

The project consists in a small robot which looks for wastes in a defined environment and 
informs people around him once he founds some.
He's also able to bring these wastes near the closest bin whenever there's nobody around him. It is then up to the children to throw away the wastes in the appropriate bin.
The purpose is to improve the cleanliness of our surroundings.
The robot has, in particular, an educational aim. Indeed, it would rather be used in 
pedagogical activities organized by teachers - mainly in primary school - to 
make children aware of cleanliness and garbage sorting. 

*Notes concenant le rapport*

Les différentes pages du document sont rédigées en utilisant le langage
AsciiDoc. Le squelette de rapport contient des exemples avec entre autre:

* des images,
* des liens,
* des équations.

La structure du rapport (parties, sections et la relation avec les
differents fichiers) se trouve dans le fichier courant.

// en PDF on ne peut pas controler la position de la toc
// Macros non supportées
ifndef::backend-pdf[]
== Table des matières
:toc-title:
toc::[]
endif::[]

// On numérote le reste des sections
:sectnums:

== Étude d’antériorité et justification de la proposition (PAN1)

include::proposition/proposition.adoc[Description de la proposition]

include::proposition/etat-de-l-art.adoc[Description de l’état de l’art]

== Scénarios d’usage (PAN1)

include::scenario/scenario.adoc[Scénarios d’usage]

<<<

== Architecture du projet (PAN1)

include::architecture/schema.adoc[Schéma d’architecture]

include::architecture/interfaces.adoc[Description des interfaces]

include::architecture/sequence.adoc[Diagramme de séquence]

include::architecture/ihm.adoc[Interface utilisateur graphique]

include::architecture/taches.adoc[Tableau détaillé des tâches]

<<<

== Organisation du projet (PAN1)

include::organisation/planification.adoc[Diagramme de planification temporel des tâches]

include::organisation/repartition.adoc[Répartition des élèves par module]

include::organisation/plan-tests.adoc[Plans de test (PAN2+)]

<<<

[bibliography]
== Bibliographie (PAN1+)

include::References.adoc[Bibliographie]

<<<

== Annexes

include::annexes/modifications.adoc[Modifications (PAN2+)]

include::annexes/avancement.adoc[Avancement des modules]

include::annexes/moduleX.adoc[Avancement module X]

include::annexes/moduleY.adoc[Avancement module Y]
