# Generated by Django 3.0.5 on 2020-04-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dechet',
            name='reponseEleve',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
