=== Description des interfaces (PAN1 / PAN2)

////
Pour le PAN1, il faut identifier et décrire sommairement toutes les
interfaces entre modules.

Pour le PAN2, il faut une description complète des interfaces.

Il faut ici une description textuelle de chaque interface, c’est à
dire +
chaque échange entre deux blocs. Si c’est une interface entre deux
blocs +
informatiques, c’est une interface Java. S’il y a des échanges de +
données complexes, il faut en décrire le format avec grande précision.
Si c’est une interface +
entre deux blocs électroniques, c’est une description des signaux +
électroniques. Etc.
////

==== InterfaceBloc1-3

(1 -> 3)
- initialisation de la base de données des enfants
- requête des statistiques
- gestion de l'activité (modes du robot)

(3 -> 1)
- envoi des statistiques analysées de la BDD
- transmission des bracelets des enfants à associer, pour l'initialisation de la bdd
- données d'activité du robot et de son état de fonctionnement (batterie, mode)

==== InterfaceBloc2-3

(2 -> 3)
- information sur la nature de l'objet se trouvant sur la photo traitée

(3 -> 2)
- transmission de l'image fournie par le robot

==== InterfaceBloc3-5

(3 -> 5)
- information sur la nature de l'objet transmis
- transmission de la base de donnée de la classe
- gestion des activités (modes du robot)

(5 -> 3)
- données brutes sur l'état de l'activité (intéractions, déchets trouvés, ...)
- données d'activité du robot et de son état de fonctionnement (batterie, mode)
- transmission des bracelets des enfants à associer, pour l'initialisation de la bdd

==== InterfaceBloc3-6

(3 -> 6)
- indication sur la nature des objets présents sur la photo transmise précédemment par le robot

(6 -> 3)
- transmission des photos de l'environnement du robot pour analyse

==== InterfaceBloc4-5

(4 -> 5)
- transmission des bracelets des enfants à associer, pour l'initialisation de la bdd
- transmission du nom de l'enfant en intéraction avec le robot (celui qui ramasse le déchet)

(5 -> 4)
- transmission de la base de donnée finale des enfants
