=== Description des interfaces (PAN1 / PAN2)

////
Pour le PAN1, il faut identifier et décrire sommairement toutes les
interfaces entre modules.

Pour le PAN2, il faut une description complète des interfaces.

Il faut ici une description textuelle de chaque interface, c’est à
dire +
chaque échange entre deux blocs. Si c’est une interface entre deux
blocs +
informatiques, c’est une interface Java. S’il y a des échanges de +
données complexes, il faut en décrire le format avec grande précision.
Si c’est une interface +
entre deux blocs électroniques, c’est une description des signaux +
électroniques. Etc.
////

==== InterfaceBloc1-2

Ajout des utilisateurs sur l'application en scannant les QR codes des bracelets des enfants.

==== InterfaceBloc2-3

A chaque fois qu'un enfant ramasse un déchet, il s'identifie auprès du robot qui lui scanne son QR code.

==== InterfaceBloc1-7

(APPLICATION -> SERVEUR)
- initialisation de la base de données des enfants
- requête des statistiques

(SERVEUR -> APPLICATION)
- envoi des statistiques de la BDD

==== InterfaceBloc3-7

(ROBOT -> SERVEUR)
- envoi des données brutes sur les interactions avec les enfants et les déchets trouvés

==== InterfaceBloc1-3

(APPLICATION -> ROBOT)
- gestion des activités (modes du robot)

(ROBOT -> APPLICATION)
- données d'activité, information sur l'état de fonctionnement (batterie, mode, ...)

==== InterfaceBloc4-5

Reconnaissance des déchets

==== InterfaceBloc4-6

Communique l'action visuelle et sonore à faire
