=== Tableau détaillé des tâches

****Note : 2 pages max - les fiches modules seront placées en annexe,
elles doivent être rédigées avec l’expert.****

Les différents aspects du projet sont découpés en tâches numérotées et
hiérarchisées (Tâches/sous-tâches, etc.). Chaque tâche est décrite
précisément et une équipe (typiquement un binôme) est affecté à sa
réalisation. Un module est typiquement constitué de plusieurs tâches et
sous-tâches. Pour le PAN3, vous aurez à démontrer une version simple,
*intégrée* et fonctionnelle de ce projet, nommée « prototype allégé ».
Dans le Tableau 1, complétez la colonne « Intégrée au PAN3 » comme
suit :

* Intégrée au PAN3 : la sous-tâche est soit finie soit en cours et
intégrée dans le prototype allégé.
* Non-intégrée au PAN3 : la sous-tâche est en cours, mais non intégrée
dans le prototype allégé, l’intégration se fera pour PAN4. L’avancement
de la sous-tâche sera donc démontré au PAN3 indépendamment du prototype
allégé (code MatLab ou autre)

Certaines sous-tâches peuvent ne pas être démontrables dans le prototype
allégé. Mettez-vous d’accord avec vos experts techniques pour savoir ce
qu’il est réaliste de démontrer au PAN3. N’hésitez pas à redécouper en 2
sous-taches, l’une démontrable au PAN3 et l’autre uniquement au PAN4.

[cols=",,^",options="header",]
|====
| Tâche | Description                                           | Intégré au PAN3
| T1    | Classificateur d’image                                |
| T1.1  | Changement espace de couleur pour permettre …         | X
| T1.2  | Extraction de l’histogramme à partir de l’espace XYZ… | X
| T1.3  | Extraction des caractéristiques …                     |
| T1.4  | Comparaison des caractéristiques                      | X
| T2    | Détection de rythme (Module « Audio/Rythme »)         |
| T2.1  | Découpage signal sonore en bande fréquentielle        | X
| T2.2  | Détection du tempo                                    |
| T2.3  | Changement de tempo                                   | X
|====
