=== Scénarios d’usage

Après avoir remporté avec brio un concours jeunes talents organisé par le ministère de l’éducation nationale, la startup telecomienne à l’origine du robot “Wall-Ed” dépose un mystérieux colis dans la boîte au lettre d’Estelle, professeur des écoles en maternelle. Celle-ci quitte sa maison avec le colis sous le bras et part en direction de l’école.

“Bonjour les enfants, veuillez accueillir de nouveaux camarades : les robots Wall-Ed” dit l’institutrice en entrant dans la classe. Elle sort alors les robots de leurs emballages, les allume et les pose au sol. Ces robots colorés se mettent alors à clignoter et l'un d'eux prend la parole d’une voix amicale, s’adressant à Estelle.

“Bonjour ! Je m’appelle Wall-Ed . Nous allons débuter ma configuration. Veuillez sortir votre téléphone portable, télécharger l’application Wall-Ed et enfin distribuer un bracelet à chaque élève.”

Estelle ouvre l’application et suit les instructions : chaque enfant s'enregistre (nom, prénom) et choisit un bracelet coloré (le set de bracelets étant livré avec les robots), qui permettra par la suite au robot d'identifier chaque élève. L’activité pédagogique peut alors commencer : l'institutrice dispose de manière aléatoire des déchets de différents types dans l’espace choisi. Les robots débutent leur mission : ils se lancent dans la recherche de déchets en se repérant dans l’espace à l’aide de leur caméra et des sons qu’ils perçoivent.

Ils se déplacent de manière à balayer la pièce dans laquelle ils se trouvent (salle de classe ou cour de récréation) en évitant les obstacles, jusqu’à ce qu’ils détectent un déchet au sol (sachet plastique, canette, bout de papier,…). Ils se dirigent alors en direction de ce dernier.

Une fois qu’un robot a trouvé un déchet, il émet un signal sonore (à l'aide de hauts-parleurs) et lumineux (système de leds) afin d’attirer l’attention des enfants : le robot affiche alors sur un écran intégré à sa coque deux prénoms d’élèves (de manière aléatoire parmi les noms de la base de données). Les enfants circulent ainsi dans la pièce à la recherche d’un robot qui indique leur nom : le premier des deux enfants qui arrive en face du robot passe son bracelet devant la caméra du robot afin que celui-ci valide son identité, puis appuie sur le bouton (présent sur la coque du robot) de couleur qui correspond à la bonne couleur de poubelle dans laquelle le déchet doit être jeté (afin de sensibiliser les enfants au recyclage). Le robot félicite ou corrige l’enfant selon la réponse, et l'enfant peut aller jeter le déchêt dans la bonne poubelle.

S’il n’a pas de réponse au bout d’un certain temps, il émet un signal différent et plus intense. S’il se rend compte qu’il n’y a pas d’enfants à proximité, il se met en veille.

Via l’application, Estelle a accès aux scores de ses élèves : les enfants ayant les meilleures scores se verront récompensés à la fin de l'activité. Le reste des données (réussite / échec de l’enfant à identifier le déchet, statistiques par classes, enfants, …) est collecté en temps réel : les enseignants peuvent les consulter via l’application Wall-Ed. Celles-ci sont également accessibles à la startup qui pourra les analyser (temps avant de trouver un déchet, avant de trouver un enfant, …) afin de pouvoir, par la suite, optimiser les fonctionnalités du robot.